### ISSUE TITLE
Thumbnail CSS rule negatively affecting Vanilla UI by cropping thumbnails

### ISSUE THREAD

**Issue by rocketgarden** [AlUlkesh/stable-diffusion-webui-images-browser#189]
The recently added CSS rule
```css
.thumbnail-item > img {
  width: auto !important;
  height: auto !important;
}
```
Is causing thumbnails in the txt2image tab to crop to square, which is undesirable (since one presumably wants to see the entire image they have just generated, at a glance).

This was recently reported in the WebUI repo but seems to be caused by this plugin.
https://github.com/AUTOMATIC1111/stable-diffusion-webui/issues/10827
